#!/bin/bash
SYSLOG=/var/log/syslog
NDASID1=9L5HC-J0SFA-7XNG6-A6X5X
NDASWK1=RHN6A
NDASNAME1=nd10
NDASID2=3V1MX-PKQB6-50E36-Y03R4
NDASWK2=XNH3K
NDASNAME2=351une

echo "*************************************************  Clear Logs"
cat /dev/null > $SYSLOG

echo " " >> $SYSLOG
echo " " >> $SYSLOG
echo "*************************************************  Register 500gig " >> $SYSLOG
ndasadmin register $NDASID1-$NDASWK1 -n $NDASNAME1
sleep 5

echo " " >> $SYSLOG
echo " " >> $SYSLOG
echo "*************************************************  Register 351-1 " >> $SYSLOG
ndasadmin register $NDASID2-$NDASWK2 -n $NDASNAME2
sleep 5

echo " " >> $SYSLOG
echo " " >> $SYSLOG
echo "*************************************************  List Device " >> $SYSLOG
cat /proc/ndas/devs
sleep 5

echo " " >> $SYSLOG
echo " " >> $SYSLOG
echo "*************************************************  Enable $NDASNAME " >> $SYSLOG
ndasadmin enable -s 1 -o w
sleep 5

echo " " >> $SYSLOG
echo " " >> $SYSLOG
echo "*************************************************  Enable $NDASNAME2 " >> $SYSLOG
ndasadmin enable -s 2 -o w
sleep 5

echo " " >> $SYSLOG
echo " " >> $SYSLOG
echo "*************************************************  Copy Logs" >> $SYSLOG
cat $SYSLOG > lastlogs
