#!/bin/bash
# tries to remove all ndas installed things from the debian system
# use this if you crash and need to restart without ndas
# The kernel modules will not be deleted or removes, so 
# make sure to run purge ndas after rebooting.  


rm -rf /dev/ndas
rm -rf /dev/.udev/db/ndas:ndas

rm /etc/init.d/ndas /etc/rc?.d/[SK]??ndas

rm -rf /lib/modules/*/kernel/drivers/block/ndas

rm /etc/ndas.conf

rm -rf /proc/ndas

rm -rf /sys/devices/virtual/ndas
rm -rf /sys/class/ndas
#rm -rf /sys/kernel/slab/ndas*
rm -rf /sys/module/ndas*

rm -rf /usr/lib/ndas
rm -rf /usr/sbin/ndasadmin
rm -rf /usr/share/ndas*
rm -rf /usr/share/doc/ndas*
rm -rf /usr/src/modules/ndas
rm -rf /usr/src/ndas*

rm -rf /var/cache/modass/ndas-*
rm -rf /var/lib/update-rc.d/ndas
rm -rf /var/lib/dpkg/info/ndas*

echo Now run "make clean" as normal user then rebuild. 
