#!/bin/sh

unset NDAS_CROSS_COMPILE
unset NDAS_EXTRA_CFLAGS
unset NDAS_KERNEL_ARCH
unset NDAS_KERNEL_PATH
unset NDAS_KERNEL_VERSION
unset NDAS_DEBUG

unset NDAS_OPENWRT_PATH
unset EM86XX_ARMUTILS_PATH


