#define DEBUG_LEVEL_ITF 0

#define DEBUG_LEVEL_LPX 1

#define DEBUG_LEVEL_LPX_REXMIT 0

#define DEBUG_LEVEL_LPX_DATAGRAM 0

#define DEBUG_LEVEL_LPX_STREAM 0

#define DEBUG_LEVEL_LPX_PACKET 0

#define DEBUG_LEVEL_LPX_PNP 1

#define DEBUG_LEVEL_LPX_SIO 1

#define DEBUG_LEVEL_LANSCSI 0

#define DEBUG_LEVEL_LDASUSER 0

#define DEBUG_LEVEL_NDDEV 8

#define DEBUG_LEVEL_SDEV 8

#define DEBUG_LEVEL_SDEV_LOCK 8

#define DEBUG_LEVEL_UDEV 8

#define DEBUG_LEVEL_TIR 0

#define DEBUG_LEVEL_UCONN 0

#define DEBUG_LEVEL_NDIOD 8

#define DEBUG_LEVEL_XLIB 0

#define DEBUG_LEVEL_XLIB_XBUF 0

#define DEBUG_LEVEL_RAID 0

#define DEBUG_LEVEL_JBOD 0

#define DEBUG_LEVEL_RDDC 0

#define DEBUG_LEVEL_RAIDL 0

#define DEBUG_LEVEL_RAID0 0

#define DEBUG_LEVEL_RAID0 0

#define DEBUG_LEVEL_RAID_RECOVER 0

#define DEBUG_LEVEL_RAID4 0

#define DEBUG_LEVEL_SAL_NET 8

#define DEBUG_LEVEL_SAL_NET_PACKET 8

#define DEBUG_LEVEL_SAL_TIME 8

#define DEBUG_LEVEL_SAL_SYNC 8

#define DEBUG_LEVEL_SAL_MEM 8

#define DEBUG_LEVEL_LINUX_BLOCK 8

#define DEBUG_LEVEL_NDADMIN 8

#define DEBUG_LEVEL_DPC 8

#define DEBUG_LEVEL_BPC 0

#define DEBUG_LEVEL_HIX 0

#define DEBUG_LEVEL_REGISTRAR 8

#define DEBUG_LEVEL_NDASOP 8

#define DEBUG_LEVEL_XIXFS_EVENT 0

#define DEBUG_LEVEL_NDASEMU 0

#ifndef RELEASE
#undef STAT_XBUF

#undef STAT_DPC

#undef STAT_XBUF

#undef STAT_REXMIT
#endif

