#!/bin/bash
# blank the logs

#find out if we are root access.
if  ! [ $(id -u) = 0 ]; then
   echo 
   echo "This script must be run as root." 
   echo "Try su -c \"sh $0 \" "
   echo
   exit 1
fi

if [ -f /var/log/messages ]; then
	cat /dev/null > /var/log/messages
fi 

if [ -f /var/log/kern.log ]; then
	cat /dev/null > /var/log/kern.log
fi
