#!/bin/bash
# purges all ndas installed things from the debian system
# use this if you need a fresh start after compiling 

echo disable slot 1
/usr/sbin/ndasadmin disable -s 1
wait

echo 

echo disable slot 2
/usr/sbin/ndasadmin disable -s 2
wait

echo

sh /etc/init.d/ndas stop
wait
#rmmod ndas_block
#rmmod ndas_core
#rmmod ndas_sal

rm -rf /dev/ndas
rm -rf /dev/.udev/db/ndas:ndas

rm /etc/init.d/ndas /etc/rc?.d/[SK]??ndas

rm -rf /lib/modules/*/kernel/drivers/block/ndas

rm /etc/ndas.conf

rm -rf /proc/ndas

rm -rf /sys/devices/virtual/ndas
rm -rf /sys/class/ndas
rm -rf /sys/module/ndas*

rm -rf /usr/lib/ndas
rm -rf /usr/sbin/ndasadmin
rm -rf /usr/share/ndas*
rm -rf /usr/share/doc/ndas*
rm -rf /usr/src/modules/ndas
rm -rf /usr/src/ndas*

rm -rf /var/cache/modass/ndas-*
rm -rf /var/lib/update-rc.d/ndas
rm -rf /var/lib/dpkg/info/ndas*

echo now do \"make clean\" to get ready for rebuilding.
