# -------------------------------------------------------------------------
# Copyright (c) IOCELL Networks Corp., Plainsboro NJ 08536, USA
# All rights reserved.
# -------------------------------------------------------------------------
#
# ndas for linux v 2.6
# Makefile

#
# Find out the current src root directory
#
NDAS4LINUX_HOME?=$(shell pwd)
nxp-root=$(NDAS4LINUX_HOME)

include $(nxp-root)/arch/config.mk
include $(nxp-root)/ndaslinux.mk
include $(nxp-root)/common.mk
include $(nxp-root)/arch/targets.mk
